#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

apt-get -y update
apt-get -y install nginx

sed -i "12i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

systemctl restart nginx
